update the release script

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,31 +1,213 @@
-# Use the latest 2.1 version of CircleCI pipeline process engine.
-# See: https://circleci.com/docs/reference/configuration-reference
 version: 2.1
 
-# Define a job to be invoked later in a workflow.
-# See: https://circleci.com/docs/guides/orchestrate/jobs-steps/#jobs-overview & https://circleci.com/docs/reference/configuration-reference/#jobs
-jobs:
-  say-hello:
-    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
-    # See: https://circleci.com/docs/guides/execution-managed/executor-intro/ & https://circleci.com/docs/reference/configuration-reference/#executor-job
-    docker:
-      # Specify the version you desire here
-      # See: https://circleci.com/developer/images/image/cimg/base
-      - image: cimg/base:current
-
-    # Add steps to the job
-    # See: https://circleci.com/docs/guides/orchestrate/jobs-steps/#steps-overview & https://circleci.com/docs/reference/configuration-reference/#steps
+# Commands
+commands:
+  notify:
+    description: "Send notification to Google Chat"
+    parameters:
+      when:
+        type: enum
+        default: "success"
+        enum: ["failure", "success", "running"]
+      webhook:
+        type: string
     steps:
-      # Checkout the code as the first step.
+      - when:
+          condition:
+            equal: [ "failure", << parameters.when >> ]
+          steps:
+            - run:
+                name: Sending notification
+                when: on_fail
+                command: |
+                  export CARD_IMG_URL="https://static-00.iconduck.com/assets.00/error-o-icon-512x512-aq7fhgxm.png"
+                  export CARD_TITLE="Pipeline Failed"
+                  export COMMIT_SHA="<< pipeline.trigger_parameters.github_app.commit_sha >>"
+                  export SHORT_COMMIT_SHA=${COMMIT_SHA:0:8}
+                  export SHORT_WORKFLOW_ID=${CIRCLE_WORKFLOW_ID:0:8}
+                  export API_RESPONSE=$( curl --request GET --url https://circleci.com/api/v2/workflow/${CIRCLE_WORKFLOW_ID} --header 'Circle-Token: ${CIRCLE_TOKEN}' )
+                  export PIPELINE_NUM=$( echo ${API_RESPONSE} | jq -r '.pipeline_number' )
+                  export WORKFLOW_NAME=$( echo ${API_RESPONSE} | jq -r '.name' )
+                  export WORKFLOW_URL="https://app.circleci.com/pipelines/workflows/${CIRCLE_WORKFLOW_ID}"
+                  curl --header "Content-Type: application/json" \
+                    --request POST \
+                    --data "{\"cardsV2\":[{\"cardId\":\"pipeline_card\",\"card\":{\"header\":{\"title\":\"${CARD_TITLE}\",\"subtitle\":\"Workflow ${SHORT_WORKFLOW_ID} at << pipeline.trigger_parameters.github_app.repo_name >>\",\"imageUrl\":\"${CARD_IMG_URL}\",\"imageType\":\"CIRCLE\",\"imageAltText\":\"status image\"},\"sections\":[{\"header\":\"Pipeline Details\",\"collapsible\":false,\"widgets\":[{\"decoratedText\":{\"startIcon\":{\"iconUrl\":\"https://static-00.iconduck.com/assets.00/git-branch-icon-506x512-cvb8ut16.png\"},\"text\":\"${CIRCLE_BRANCH}\",\"onClick\":{\"openLink\":{\"url\":\"<< pipeline.trigger_parameters.github_app.web_url >>/tree/${CIRCLE_BRANCH}\"}}}},{\"decoratedText\":{\"startIcon\":{\"iconUrl\":\"https://static.thenounproject.com/png/2537955-200.png\", \"imageType\": \"CIRCLE\"},\"onClick\":{\"openLink\":{\"url\":\"<< pipeline.trigger_parameters.github_app.web_url >>/commit/${COMMIT_SHA}\"}},\"text\":\"<b>(${SHORT_COMMIT_SHA})</b> << pipeline.trigger_parameters.github_app.commit_title >>\"}},{\"decoratedText\":{\"startIcon\":{\"iconUrl\":\"https://static.thenounproject.com/png/3499262-200.png\"},\"text\":\"${CIRCLE_WORKFLOW_ID}\",\"onClick\":{\"openLink\":{\"url\":\"${WORKFLOW_URL}\"}}}},{\"decoratedText\":{\"startIcon\":{\"iconUrl\":\"https://static-00.iconduck.com/assets.00/user-icon-512x512-u0spsrd0.png\"},\"text\":\"<< pipeline.trigger_parameters.github_app.user_name >>\"}},{\"buttonList\":{\"buttons\":[{\"text\":\"View Pipeline\",\"onClick\":{\"openLink\":{\"url\":\"${WORKFLOW_URL}\"}}}]}}]}]}}]}" \
+                    "<< parameters.webhook >>"
+      - when:
+          condition:
+            equal: [ "success", << parameters.when >> ]
+          steps:
+            - run:
+                name: Sending notification
+                when: on_success
+                command: |
+                  export CARD_IMG_URL="https://static-00.iconduck.com/assets.00/right-o-icon-512x512-60i1xoud.png"
+                  export CARD_TITLE="Pipeline Succeeded"
+                  export COMMIT_SHA="<< pipeline.trigger_parameters.github_app.commit_sha >>"
+                  export SHORT_COMMIT_SHA=${COMMIT_SHA:0:8}
+                  export SHORT_WORKFLOW_ID=${CIRCLE_WORKFLOW_ID:0:8}
+                  export API_RESPONSE=$( curl --request GET --url https://circleci.com/api/v2/workflow/${CIRCLE_WORKFLOW_ID} --header 'Circle-Token: ${CIRCLE_TOKEN}' )
+                  export PIPELINE_NUM=$( echo ${API_RESPONSE} | jq -r '.pipeline_number' )
+                  export WORKFLOW_NAME=$( echo ${API_RESPONSE} | jq -r '.name' )
+                  export WORKFLOW_URL="https://app.circleci.com/pipelines/workflows/${CIRCLE_WORKFLOW_ID}"
+                  curl --header "Content-Type: application/json" \
+                    --request POST \
+                    --data "{\"cardsV2\":[{\"cardId\":\"pipeline_card\",\"card\":{\"header\":{\"title\":\"${CARD_TITLE}\",\"subtitle\":\"Workflow ${SHORT_WORKFLOW_ID} at << pipeline.trigger_parameters.github_app.repo_name >>\",\"imageUrl\":\"${CARD_IMG_URL}\",\"imageType\":\"CIRCLE\",\"imageAltText\":\"status image\"},\"sections\":[{\"header\":\"Pipeline Details\",\"collapsible\":false,\"widgets\":[{\"decoratedText\":{\"startIcon\":{\"iconUrl\":\"https://static-00.iconduck.com/assets.00/git-branch-icon-506x512-cvb8ut16.png\"},\"text\":\"${CIRCLE_BRANCH}\",\"onClick\":{\"openLink\":{\"url\":\"<< pipeline.trigger_parameters.github_app.web_url >>/tree/${CIRCLE_BRANCH}\"}}}},{\"decoratedText\":{\"startIcon\":{\"iconUrl\":\"https://static.thenounproject.com/png/2537955-200.png\", \"imageType\": \"CIRCLE\"},\"onClick\":{\"openLink\":{\"url\":\"<< pipeline.trigger_parameters.github_app.web_url >>/commit/${COMMIT_SHA}\"}},\"text\":\"<b>(${SHORT_COMMIT_SHA})</b> << pipeline.trigger_parameters.github_app.commit_title >>\"}},{\"decoratedText\":{\"startIcon\":{\"iconUrl\":\"https://static.thenounproject.com/png/3499262-200.png\"},\"text\":\"${CIRCLE_WORKFLOW_ID}\",\"onClick\":{\"openLink\":{\"url\":\"${WORKFLOW_URL}\"}}}},{\"decoratedText\":{\"startIcon\":{\"iconUrl\":\"https://static-00.iconduck.com/assets.00/user-icon-512x512-u0spsrd0.png\"},\"text\":\"<< pipeline.trigger_parameters.github_app.user_name >>\"}},{\"buttonList\":{\"buttons\":[{\"text\":\"View Pipeline\",\"onClick\":{\"openLink\":{\"url\":\"${WORKFLOW_URL}\"}}}]}}]}]}}]}" \
+                    "<< parameters.webhook >>"
+      - when:
+          condition:
+            equal: [ "running", << parameters.when >> ]
+          steps:
+            - run:
+                name: Sending notification
+                command: |
+                  export CARD_IMG_URL="https://static-00.iconduck.com/assets.00/running-o-icon-512x512-ch5zuanx.png"
+                  export CARD_TITLE="Pipeline Running"
+                  export COMMIT_SHA="<< pipeline.trigger_parameters.github_app.commit_sha >>"
+                  export SHORT_COMMIT_SHA=${COMMIT_SHA:0:8}
+                  export API_RESPONSE=$( curl --request GET --url https://circleci.com/api/v2/workflow/${CIRCLE_WORKFLOW_ID} --header 'Circle-Token: ${CIRCLE_TOKEN}' )
+                  export SHORT_WORKFLOW_ID=${CIRCLE_WORKFLOW_ID:0:8}
+                  export PIPELINE_NUM=$( echo ${API_RESPONSE} | jq -r '.pipeline_number' )
+                  export WORKFLOW_NAME=$( echo ${API_RESPONSE} | jq -r '.name' )
+                  export WORKFLOW_URL="https://app.circleci.com/pipelines/workflows/${CIRCLE_WORKFLOW_ID}"
+                  curl --header "Content-Type: application/json" \
+                    --request POST \
+                    --data "{\"cardsV2\":[{\"cardId\":\"pipeline_card\",\"card\":{\"header\":{\"title\":\"${CARD_TITLE}\",\"subtitle\":\"Workflow ${SHORT_WORKFLOW_ID} at << pipeline.trigger_parameters.github_app.repo_name >>\",\"imageUrl\":\"${CARD_IMG_URL}\",\"imageType\":\"CIRCLE\",\"imageAltText\":\"status image\"},\"sections\":[{\"header\":\"Pipeline Details\",\"collapsible\":false,\"widgets\":[{\"decoratedText\":{\"startIcon\":{\"iconUrl\":\"https://static-00.iconduck.com/assets.00/git-branch-icon-506x512-cvb8ut16.png\"},\"text\":\"${CIRCLE_BRANCH}\",\"onClick\":{\"openLink\":{\"url\":\"<< pipeline.trigger_parameters.github_app.web_url >>/tree/${CIRCLE_BRANCH}\"}}}},{\"decoratedText\":{\"startIcon\":{\"iconUrl\":\"https://static.thenounproject.com/png/2537955-200.png\", \"imageType\": \"CIRCLE\"},\"onClick\":{\"openLink\":{\"url\":\"<< pipeline.trigger_parameters.github_app.web_url >>/commit/${COMMIT_SHA}\"}},\"text\":\"<b>(${SHORT_COMMIT_SHA})</b> << pipeline.trigger_parameters.github_app.commit_title >>\"}},{\"decoratedText\":{\"startIcon\":{\"iconUrl\":\"https://static.thenounproject.com/png/3499262-200.png\"},\"text\":\"${CIRCLE_WORKFLOW_ID}\",\"onClick\":{\"openLink\":{\"url\":\"${WORKFLOW_URL}\"}}}},{\"decoratedText\":{\"startIcon\":{\"iconUrl\":\"https://static-00.iconduck.com/assets.00/user-icon-512x512-u0spsrd0.png\"},\"text\":\"<< pipeline.trigger_parameters.github_app.user_name >>\"}},{\"buttonList\":{\"buttons\":[{\"text\":\"View Pipeline\",\"onClick\":{\"openLink\":{\"url\":\"${WORKFLOW_URL}\"}}}]}}]}]}}]}" \
+                    "<< parameters.webhook >>"
+
+  send-message:
+    description: "Send a custom message to Google Chat"
+    parameters:
+      when:
+        type: enum
+        default: "running"
+        enum: ["failure", "success", "running"]
+      message:
+        type: string
+      webhook:
+        type: string
+    steps:
+      - when:
+          condition:
+            equal: [ "failure", << parameters.when >> ]
+          steps:
+            - run:
+                name: Sending message
+                when: on_fail
+                command: |
+                  export SHORT_WORKFLOW_ID=${CIRCLE_WORKFLOW_ID:0:8}
+                  export WORKFLOW_URL="https://app.circleci.com/pipelines/workflows/${CIRCLE_WORKFLOW_ID}"
+                  curl --header "Content-Type: application/json" \
+                    --request POST \
+                    --data "{\"text\": \"*Message from job ${CIRCLE_JOB} of workflow <${WORKFLOW_URL}|${SHORT_WORKFLOW_ID}>*\\n<< parameters.message >>\"}" \
+                    "<< parameters.webhook >>"
+      - when:
+          condition:
+            equal: [ "success", << parameters.when >> ]
+          steps:
+            - run:
+                name: Sending message
+                when: on_success
+                command: |
+                  export SHORT_WORKFLOW_ID=${CIRCLE_WORKFLOW_ID:0:8}
+                  export WORKFLOW_URL="https://app.circleci.com/pipelines/workflows/${CIRCLE_WORKFLOW_ID}"
+                  curl --header "Content-Type: application/json" \
+                    --request POST \
+                    --data "{\"text\": \"*Message from job ${CIRCLE_JOB} of workflow <${WORKFLOW_URL}|${SHORT_WORKFLOW_ID}>*\\n<< parameters.message >>\"}" \
+                    "<< parameters.webhook >>"
+      - when:
+          condition:
+            equal: [ "running", << parameters.when >> ]
+          steps:
+            - run:
+                name: "Send custom message to Google Chat"
+                command: |
+                  export SHORT_WORKFLOW_ID=${CIRCLE_WORKFLOW_ID:0:8}
+                  export WORKFLOW_URL="https://app.circleci.com/pipelines/workflows/${CIRCLE_WORKFLOW_ID}"
+                  curl --header "Content-Type: application/json" \
+                    --request POST \
+                    --data "{\"text\": \"*Message from job ${CIRCLE_JOB} of workflow <${WORKFLOW_URL}|${SHORT_WORKFLOW_ID}>*\\n<< parameters.message >>\"}" \
+                    "<< parameters.webhook >>"
+
+# Macros
+default-context: &default-context
+  context:
+    - movelai-global
+    - movelai-ros
+
+master-branch: &master-branch
+  filters:
+    branches:
+      only:
+        - master
+        - circleci-project-setup  # TEMP(Stage 2 test): remove before merge to master
+
+executors:
+  cimg-base:
+    docker:
+      - image: cimg/base:stable
+    working_directory: /tmp/build
+  docker-alpine:
+    docker:
+      - image: alpine:3.18.0
+    working_directory: /tmp/build
+
+jobs:
+  build_and_release:
+    executor: cimg-base
+    steps:
       - checkout
       - run:
-          name: "Say hello"
-          command: "echo Hello, World!"
+          name: Install build tools
+          command: |
+            sudo apt-get update
+            sudo apt-get install -y zip
+            # cimg/base ships git, curl, jq, and the GitHub CLI (gh).
+            command -v git >/dev/null || sudo apt-get install -y git
+            command -v curl >/dev/null || sudo apt-get install -y curl
+            command -v jq >/dev/null || sudo apt-get install -y jq
+            command -v gh >/dev/null || { echo "GitHub CLI (gh) missing; cannot upload releases"; exit 1; }
+      - run:
+          name: Build and publish Easy Deploy release
+          command: |
+            # gh authenticates via GH_TOKEN; the config clone uses GITHUB_USER/GITHUB_TOKEN.
+            export GH_TOKEN="${GITHUB_TOKEN}"
+            bash scripts/release.sh --no-upload  # TEMP(Stage 2 test): remove --no-upload before merge to master
+      - run:
+          name: Summarize produced assets
+          when: always
+          command: |
+            echo "=== dist/manifest.json ==="
+            cat dist/manifest.json 2>/dev/null || echo "(no manifest.json)"
+            echo "=== dist assets ==="
+            ls -lh dist/*.zip 2>/dev/null || echo "(no zips produced)"
+      - notify:
+          when: "failure"
+          webhook: ${GOOGLE_CHAT_WEBHOOK}
 
-# Orchestrate jobs using workflows
-# See: https://circleci.com/docs/guides/orchestrate/workflows/ & https://circleci.com/docs/reference/configuration-reference/#workflows
+  notify-pipeline-success:
+    executor: docker-alpine
+    resource_class: small
+    steps:
+      - run:
+          name: Install tools
+          command: apk add --no-cache curl jq
+      - notify:
+          when: "success"
+          webhook: ${GOOGLE_CHAT_WEBHOOK}
+      - send-message:
+          when: "success"
+          message: "Easy Deploy release pipeline finished successfully for branch ${CIRCLE_BRANCH}."
+          webhook: ${GOOGLE_CHAT_MSG_WEBHOOK}
+
 workflows:
-  say-hello-workflow: # This is the name of the workflow, feel free to change it to better match your workflow.
-    # Inside the workflow, you define the jobs you want to run.
+  easy_deploy_release:
     jobs:
-      - say-hello
+      - build_and_release:
+          <<: *default-context
+          <<: *master-branch
+      - notify-pipeline-success:
+          <<: *default-context
+          <<: *master-branch
+          requires:
+            - build_and_release
